package:
  name: arts_crossfit
  version: "0.0"

source:
  git_rev: v0.1
  git_url: https://github.com/menzel-gfdl/arts-crossfit.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - numpy
    - scipy
    - xarray

about:
    home: https://github.com/menzel-gfdl/arts-crossfit
